name: Compile and Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: ./compile.sh
        shell: bash

      - name: Create Signature
        uses: FKLC/sign-files-action@v1.0.0
        with:
          privateKey: ${{ secrets.PK }}
          passphrase: ${{ secrets.PK_PASSPHRASE }}
          outputFolder: build/
          files: |
            build/**

      - name: Upload binary and signature as artifact
        uses: actions/upload-artifact@v3
        with:
          name: stj
          path: build/

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download complied binaries and signatures
        uses: actions/download-artifact@v3
        with:
          path: builds

      - name: Make a draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: builds/**
